use anyhow::Result;
use wasm_workers_rs::{handler, http::{self, Request, Response, response}, cache::Cache};

#[handler(cache)]
fn reply(req: Request<String>, cache: &mut Cache) -> Result<Response<String>> {

    let count = cache.get("counter");
    let count_num = match count {
        Some(count_str) => count_str.parse::<u32>().unwrap_or(0),
        None => 0,
    };
    let response = format!(
        "<!DOCTYPE html>
<body>
<h1>キー/バリューストア in Rust</h1>
<p>カウンター: {}</p>
<p>This page was generated by a Wasm modules built from Rust.</p>
</body>",
        count_num
    );

    cache.insert("counter".to_string(), (count_num + 1).to_string());

    Ok(http::Response::builder()
        .status(200)
        .header("x-generated-by", "wasm-workers-server")
        .body(response.into())?)
}